#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any, Mapping


def render_uarch_override_schema_cpp(payload: Mapping[str, Any]) -> str:
    lines = [
        "// Generated by tools/generate_uarch_override_schema_cpp.py. Do not edit.",
        "static constexpr GeneratedUarchField kGeneratedUarchFields[] = {",
    ]
    for name, spec in payload["fields"].items():
        targets = set(spec["targets"])
        lines.append(
            f"  {{{json.dumps(name)}, {json.dumps(spec['type'])}, "
            f"{'true' if 'python' in targets else 'false'}, "
            f"{'true' if 'cpp' in targets else 'false'}}},"
        )
    lines.extend(
        [
            "};",
            "static constexpr const char *kGeneratedDeprecatedUarchFields[] = {",
        ]
    )
    for name in payload.get("deprecated_fields", []):
        lines.append(f"  {json.dumps(name)},")
    lines.extend(["};", ""])
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("source", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    payload = json.loads(args.source.read_text(encoding="utf-8"))
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(
        render_uarch_override_schema_cpp(payload), encoding="utf-8"
    )


if __name__ == "__main__":
    main()
