#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any, Mapping


def _quote(value: str) -> str:
    return json.dumps(value)


def render_catalog_cpp(payload: Mapping[str, Any]) -> str:
    instructions = payload["instructions"]
    lines = [
        "// Generated by tools/generate_instruction_catalog_cpp.py. Do not edit.",
        "static constexpr GeneratedInstruction kGeneratedInstructions[] = {",
    ]
    for opcode, spec in instructions.items():
        lines.append(
            "  {%s, %s, %s, %s, %s, %s, %s, %d},"
            % (
                _quote(opcode),
                _quote(spec["class"]),
                _quote(spec["signature"]),
                _quote(spec.get("form_rule", "operand_dtype")),
                _quote(spec.get("fixed_form", "")),
                "true" if spec.get("virtual", False) else "false",
                _quote(spec.get("align_state_operation", "")),
                int(spec.get("align_state_argument_index", -1)),
            )
        )
    lines.append("};")
    lines.append("static constexpr GeneratedOperand kGeneratedOperands[] = {")
    signatures = payload["signatures"]
    for opcode, spec in instructions.items():
        for operand in signatures[spec["signature"]]:
            lines.append(
                "  {%s, %s, %d, %s, %s, %s, %s, %s},"
                % (
                    _quote(opcode),
                    _quote(operand["name"]),
                    operand["argument_index"],
                    _quote(operand["direction"]),
                    _quote(operand["role"]),
                    _quote(operand["kind"]),
                    "true" if operand.get("optional", False) else "false",
                    "true"
                    if operand.get("allow_integer_expression", False)
                    else "false",
                )
            )
    lines.append("};")
    lines.append("static constexpr GeneratedAllowedValue kGeneratedAllowedValues[] = {")
    for opcode, spec in instructions.items():
        for operand in signatures[spec["signature"]]:
            for value in operand.get("allowed_values", []):
                lines.append(
                    "  {%s, %d, %s},"
                    % (
                        _quote(opcode),
                        operand["argument_index"],
                        _quote(value),
                    )
                )
    lines.append("};")
    lines.append("static constexpr GeneratedCallVariant kGeneratedCallVariants[] = {")
    for opcode, spec in instructions.items():
        for variant_index, variant in enumerate(spec.get("call_variants", [])):
            lines.append(
                "  {%s, %d, %d},"
                % (_quote(opcode), variant_index, variant["argument_count"])
            )
    lines.append("};")
    lines.append(
        "static constexpr GeneratedCallVariantValue "
        "kGeneratedCallVariantValues[] = {"
    )
    for opcode, spec in instructions.items():
        for variant_index, variant in enumerate(spec.get("call_variants", [])):
            for argument_index, values in variant.get("argument_values", {}).items():
                for value in values:
                    lines.append(
                        "  {%s, %d, %d, %s},"
                        % (
                            _quote(opcode),
                            variant_index,
                            int(argument_index),
                            _quote(value),
                        )
                    )
    lines.append("};")
    lines.append("static constexpr GeneratedAlias kGeneratedAliases[] = {")
    for opcode, spec in instructions.items():
        for alias in spec.get("aliases", []):
            lines.append(f"  {{{_quote(alias)}, {_quote(opcode)}}},")
    lines.append("};")
    lines.append("static constexpr GeneratedForm kGeneratedForms[] = {")
    for opcode, spec in instructions.items():
        for form in spec.get("forms", []):
            lines.append(f"  {{{_quote(opcode)}, {_quote(form)}}},")
    lines.append("};")
    lines.append(
        "static constexpr GeneratedSpecialization kGeneratedSpecializations[] = {"
    )
    for opcode, spec in instructions.items():
        for form, target in spec.get("specializations", {}).items():
            lines.append(
                f"  {{{_quote(opcode)}, {_quote(form)}, {_quote(target)}}},"
            )
    lines.append("};")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("source", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    payload = json.loads(args.source.read_text())
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(render_catalog_cpp(payload))


if __name__ == "__main__":
    main()
